[package]
name = "oha"
version = "0.1.5"
authors = ["hatoo <hato2000@gmail.com>"]
edition = "2018"
description = "Ohayou(おはよう), HTTP load generator, inspired by rakyll/hey with tui animation."
repository = "https://github.com/hatoo/oha"
readme = "README.md"
keywords = ["cli", "load-testing", "performance", "http"]
categories = ["command-line-utilities", "network-programming", "web-programming::http-client", "development-tools::profiling"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
structopt = "0.3"
reqwest = { version = "0.10", features = ["gzip", "brotli"] }
tokio = { version = "0.2", features = ["full"] }
anyhow = "1"
url = "2"
crossbeam = "0.7"
futures = "0.3"
parse_duration = "2"
average = "0.10.4"
float-ord = "0.2.0"
byte-unit = "3.0.3"
tui = { version = "0.8.0", default-features = false, features = ["crossterm"] }
crossterm = "0.14.0"
rlimit = "0.3.0"
lazy_static = "1.4.0"

[dev-dependencies]
assert_cmd = "0.12.0"
warp = "0.2"
get-port = "1.3.1"
lazy_static = "1.4.0"
bytes = "0.5.4"
